---
description: "' Finally '는 ' Try ' 문 외부에 나타날 수 없습니다 .에 대 한 자세한 정보"
title: "'Finally'는 'Try' 문 외부에 사용할 수 없습니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords:
- BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
ms.openlocfilehash: 5255cf3e99faf019ce8313f75425cf18b9c9d80d
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 02/14/2021
ms.locfileid: "100472165"
---
# <a name="finally-cannot-appear-outside-a-try-statement"></a>'Finally'는 'Try' 문 외부에 사용할 수 없습니다.

`Finally` 는 `Try...Catch...Finally` 블록을 완료하는 데 사용되므로 블록의 끝에 한 번만 나타날 수 있습니다. 불필요한 `Finally`가 있거나, `Finally` 문이 해당 `Try` 블록의 경계 외부에 나타납니다.  
  
 **오류 ID:** BC30382  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1. 불필요한 `Finally` 문을 찾아서 제거합니다.  
  
2. `Finally` 문을 코드의 적절한 위치로 이동합니다.  
  
## <a name="see-also"></a>참고 항목

- [Try...Catch...Finally 문](../language-reference/statements/try-catch-finally-statement.md)
